const initialState = {
  topCities: [
    { name: 'NYC', state: 'New York' },
    { name: 'Los Angeles', state: 'California' },
    { name: 'Chicago', state: 'Illinois' },
    { name: 'Dallas', state: 'Texas' },
    { name: 'Houston', state: 'Texas' },
    { name: 'Washington', state: 'D.C.' },
    { name: 'Miami', state: 'Florida' },
    { name: 'Philadelphia', state: 'Pennsylvania' },
    { name: 'Atlanta', state: 'Georgia' },
    { name: 'Boston', state: 'Massachusetts' },
    { name: 'Phoenix', state: 'Arizona' },
    { name: 'San Francisco', state: 'California' },
    { name: 'Riverside', state: 'California' },
    { name: 'Detroit', state: 'Michigan' },
    { name: 'Seattle', state: 'Washington' },
    { name: 'Minneapolis', state: 'Minnesota' },
    { name: 'San Diego', state: 'California' },
    { name: 'Tampa', state: 'Florida' },
    { name: 'Denver', state: 'Colorado' },
    { name: 'St. Louis', state: 'Missouri' },
    { name: 'Baltimore', state: 'Maryland' },
    { name: 'Orlando', state: 'Florida' },
    { name: 'Charlotte', state: 'North Carolina' },
    { name: 'San Antonio', state: 'Texas' },
    { name: 'Portland', state: 'Oregon' },
    { name: 'Sacramento', state: 'California' },
    { name: 'Pitsburgh', state: 'Pennsylvania' },
    { name: 'Las Vegas', state: 'Nevada' },
    { name: 'Cincinnati', state: 'Ohio' },
    { name: 'Austin', state: 'Texas' },
    { name: 'Kansas City', state: 'Missouri' },
    { name: 'Columbus', state: 'Ohio' },
    { name: 'Cleveland', state: 'Ohio' },
    { name: 'Indianapolis', state: 'Indiana' },
    { name: 'San Jose', state: 'California' },
    { name: 'Nashville', state: 'Tennessee' },
    { name: 'Virginia Beach', state: 'Virginia' },
    { name: 'Providence', state: 'Rhode Island' },
    { name: 'Milwaukee', state: 'Wisconsin' },
    { name: 'Jacksonville', state: 'Florida' },
    { name: 'Oklahoma City', state: 'Oklahoma' },
    { name: 'Memphis', state: 'Tennessee' },
    { name: 'Richmond', state: 'Virginia' },
    { name: 'Louisville', state: 'Kentucky' },
    { name: 'New Orlean', state: 'Louisiana' },
    { name: 'Salt Lake City', state: 'Utah' },
    { name: 'Hartford', state: 'Connecticut' },
    { name: 'Birmingham', state: 'Alabama' },
    { name: 'Buffalo', state: 'New York' },
    { name: 'Rochester', state: 'New York' },
    { name: 'Grand Rapids', state: 'Michigan' },
    { name: 'Tuscon', state: 'Arizona' },
    { name: 'Fresno', state: 'California' },
    { name: 'Tulsa', state: 'Oklahoma' },
    { name: 'Honolulu', state: 'Hawaii' },
    { name: 'Worcester', state: 'Massachusetts' },
    { name: 'Bridgeport', state: 'Connecticut' },
    { name: 'Omaha', state: 'Nebraska' },
    { name: 'Albuquerque', state: 'New Mexico' },
    { name: 'Greenville', state: 'South Carolina' },
    { name: 'Bakersfield', state: 'California' },
    { name: 'Knoxville', state: 'Tennessee' },
    { name: 'Albany', state: 'New York' },
    { name: 'McAllen', state: 'Texas' },
    { name: 'New Haven', state: 'Connecticut' },
    { name: 'Oxnard', state: 'California' },
    { name: 'El Paso', state: 'Texas' },
  ],
};

const reducers = (state = initialState, action = {}) => {
  switch (action.type) {
    default: return state;
  }
};

export default reducers;
